[project]
name = "llm-wordlist"
version = "0.1.0"
description = "Filter a list of words using an LLM from OpenRouter"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
